# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/thinkpad/Desktop/uni/4.Semester/cg/build/cmake

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	cd /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker && $(CMAKE_COMMAND) -E cmake_progress_start /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker/CMakeFiles /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker/framework//CMakeFiles/progress.marks
	cd /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 framework/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 framework/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 framework/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 framework/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
framework/CMakeFiles/framework.dir/rule:
	cd /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 framework/CMakeFiles/framework.dir/rule
.PHONY : framework/CMakeFiles/framework.dir/rule

# Convenience name for target.
framework: framework/CMakeFiles/framework.dir/rule
.PHONY : framework

# fast build rule for target.
framework/fast:
	cd /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker && $(MAKE) $(MAKESILENT) -f framework/CMakeFiles/framework.dir/build.make framework/CMakeFiles/framework.dir/build
.PHONY : framework/fast

home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/config.o: home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/config.cpp.o
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/config.o

# target to build an object file
home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/config.cpp.o:
	cd /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker && $(MAKE) $(MAKESILENT) -f framework/CMakeFiles/framework.dir/build.make framework/CMakeFiles/framework.dir/home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/config.cpp.o
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/config.cpp.o

home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/config.i: home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/config.cpp.i
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/config.i

# target to preprocess a source file
home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/config.cpp.i:
	cd /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker && $(MAKE) $(MAKESILENT) -f framework/CMakeFiles/framework.dir/build.make framework/CMakeFiles/framework.dir/home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/config.cpp.i
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/config.cpp.i

home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/config.s: home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/config.cpp.s
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/config.s

# target to generate assembly for a file
home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/config.cpp.s:
	cd /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker && $(MAKE) $(MAKESILENT) -f framework/CMakeFiles/framework.dir/build.make framework/CMakeFiles/framework.dir/home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/config.cpp.s
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/config.cpp.s

home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/main.o: home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/main.cpp.o
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/main.o

# target to build an object file
home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/main.cpp.o:
	cd /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker && $(MAKE) $(MAKESILENT) -f framework/CMakeFiles/framework.dir/build.make framework/CMakeFiles/framework.dir/home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/main.cpp.o
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/main.cpp.o

home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/main.i: home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/main.cpp.i
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/main.i

# target to preprocess a source file
home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/main.cpp.i:
	cd /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker && $(MAKE) $(MAKESILENT) -f framework/CMakeFiles/framework.dir/build.make framework/CMakeFiles/framework.dir/home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/main.cpp.i
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/main.cpp.i

home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/main.s: home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/main.cpp.s
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/main.s

# target to generate assembly for a file
home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/main.cpp.s:
	cd /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker && $(MAKE) $(MAKESILENT) -f framework/CMakeFiles/framework.dir/build.make framework/CMakeFiles/framework.dir/home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/main.cpp.s
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/main.cpp.s

home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/obj.o: home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/obj.cpp.o
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/obj.o

# target to build an object file
home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/obj.cpp.o:
	cd /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker && $(MAKE) $(MAKESILENT) -f framework/CMakeFiles/framework.dir/build.make framework/CMakeFiles/framework.dir/home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/obj.cpp.o
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/obj.cpp.o

home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/obj.i: home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/obj.cpp.i
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/obj.i

# target to preprocess a source file
home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/obj.cpp.i:
	cd /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker && $(MAKE) $(MAKESILENT) -f framework/CMakeFiles/framework.dir/build.make framework/CMakeFiles/framework.dir/home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/obj.cpp.i
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/obj.cpp.i

home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/obj.s: home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/obj.cpp.s
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/obj.s

# target to generate assembly for a file
home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/obj.cpp.s:
	cd /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker && $(MAKE) $(MAKESILENT) -f framework/CMakeFiles/framework.dir/build.make framework/CMakeFiles/framework.dir/home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/obj.cpp.s
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/obj.cpp.s

home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/pfm.o: home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/pfm.cpp.o
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/pfm.o

# target to build an object file
home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/pfm.cpp.o:
	cd /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker && $(MAKE) $(MAKESILENT) -f framework/CMakeFiles/framework.dir/build.make framework/CMakeFiles/framework.dir/home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/pfm.cpp.o
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/pfm.cpp.o

home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/pfm.i: home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/pfm.cpp.i
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/pfm.i

# target to preprocess a source file
home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/pfm.cpp.i:
	cd /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker && $(MAKE) $(MAKESILENT) -f framework/CMakeFiles/framework.dir/build.make framework/CMakeFiles/framework.dir/home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/pfm.cpp.i
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/pfm.cpp.i

home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/pfm.s: home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/pfm.cpp.s
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/pfm.s

# target to generate assembly for a file
home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/pfm.cpp.s:
	cd /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker && $(MAKE) $(MAKESILENT) -f framework/CMakeFiles/framework.dir/build.make framework/CMakeFiles/framework.dir/home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/pfm.cpp.s
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/pfm.cpp.s

home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/png.o: home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/png.cpp.o
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/png.o

# target to build an object file
home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/png.cpp.o:
	cd /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker && $(MAKE) $(MAKESILENT) -f framework/CMakeFiles/framework.dir/build.make framework/CMakeFiles/framework.dir/home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/png.cpp.o
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/png.cpp.o

home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/png.i: home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/png.cpp.i
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/png.i

# target to preprocess a source file
home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/png.cpp.i:
	cd /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker && $(MAKE) $(MAKESILENT) -f framework/CMakeFiles/framework.dir/build.make framework/CMakeFiles/framework.dir/home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/png.cpp.i
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/png.cpp.i

home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/png.s: home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/png.cpp.s
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/png.s

# target to generate assembly for a file
home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/png.cpp.s:
	cd /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker && $(MAKE) $(MAKESILENT) -f framework/CMakeFiles/framework.dir/build.make framework/CMakeFiles/framework.dir/home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/png.cpp.s
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/png.cpp.s

home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/utils/argparse.o: home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/utils/argparse.cpp.o
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/utils/argparse.o

# target to build an object file
home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/utils/argparse.cpp.o:
	cd /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker && $(MAKE) $(MAKESILENT) -f framework/CMakeFiles/framework.dir/build.make framework/CMakeFiles/framework.dir/home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/utils/argparse.cpp.o
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/utils/argparse.cpp.o

home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/utils/argparse.i: home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/utils/argparse.cpp.i
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/utils/argparse.i

# target to preprocess a source file
home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/utils/argparse.cpp.i:
	cd /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker && $(MAKE) $(MAKESILENT) -f framework/CMakeFiles/framework.dir/build.make framework/CMakeFiles/framework.dir/home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/utils/argparse.cpp.i
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/utils/argparse.cpp.i

home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/utils/argparse.s: home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/utils/argparse.cpp.s
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/utils/argparse.s

# target to generate assembly for a file
home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/utils/argparse.cpp.s:
	cd /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker && $(MAKE) $(MAKESILENT) -f framework/CMakeFiles/framework.dir/build.make framework/CMakeFiles/framework.dir/home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/utils/argparse.cpp.s
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/utils/argparse.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... framework"
	@echo "... home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/config.o"
	@echo "... home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/config.i"
	@echo "... home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/config.s"
	@echo "... home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/main.o"
	@echo "... home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/main.i"
	@echo "... home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/main.s"
	@echo "... home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/obj.o"
	@echo "... home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/obj.i"
	@echo "... home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/obj.s"
	@echo "... home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/pfm.o"
	@echo "... home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/pfm.i"
	@echo "... home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/pfm.s"
	@echo "... home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/png.o"
	@echo "... home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/png.i"
	@echo "... home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/png.s"
	@echo "... home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/utils/argparse.o"
	@echo "... home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/utils/argparse.i"
	@echo "... home/thinkpad/Desktop/uni/4.Semester/cg/source/framework/utils/argparse.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

