# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/thinkpad/Desktop/uni/4.Semester/cg/build/cmake

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	cd /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker && $(CMAKE_COMMAND) -E cmake_progress_start /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker/CMakeFiles /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker/task1//CMakeFiles/progress.marks
	cd /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 task1/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 task1/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 task1/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 task1/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
task1/CMakeFiles/task1.dir/rule:
	cd /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 task1/CMakeFiles/task1.dir/rule
.PHONY : task1/CMakeFiles/task1.dir/rule

# Convenience name for target.
task1: task1/CMakeFiles/task1.dir/rule
.PHONY : task1

# fast build rule for target.
task1/fast:
	cd /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker && $(MAKE) $(MAKESILENT) -f task1/CMakeFiles/task1.dir/build.make task1/CMakeFiles/task1.dir/build
.PHONY : task1/fast

home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/BVH.o: home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/BVH.cpp.o
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/BVH.o

# target to build an object file
home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/BVH.cpp.o:
	cd /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker && $(MAKE) $(MAKESILENT) -f task1/CMakeFiles/task1.dir/build.make task1/CMakeFiles/task1.dir/home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/BVH.cpp.o
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/BVH.cpp.o

home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/BVH.i: home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/BVH.cpp.i
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/BVH.i

# target to preprocess a source file
home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/BVH.cpp.i:
	cd /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker && $(MAKE) $(MAKESILENT) -f task1/CMakeFiles/task1.dir/build.make task1/CMakeFiles/task1.dir/home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/BVH.cpp.i
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/BVH.cpp.i

home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/BVH.s: home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/BVH.cpp.s
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/BVH.s

# target to generate assembly for a file
home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/BVH.cpp.s:
	cd /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker && $(MAKE) $(MAKESILENT) -f task1/CMakeFiles/task1.dir/build.make task1/CMakeFiles/task1.dir/home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/BVH.cpp.s
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/BVH.cpp.s

home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/RayTracer.o: home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/RayTracer.cpp.o
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/RayTracer.o

# target to build an object file
home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/RayTracer.cpp.o:
	cd /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker && $(MAKE) $(MAKESILENT) -f task1/CMakeFiles/task1.dir/build.make task1/CMakeFiles/task1.dir/home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/RayTracer.cpp.o
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/RayTracer.cpp.o

home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/RayTracer.i: home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/RayTracer.cpp.i
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/RayTracer.i

# target to preprocess a source file
home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/RayTracer.cpp.i:
	cd /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker && $(MAKE) $(MAKESILENT) -f task1/CMakeFiles/task1.dir/build.make task1/CMakeFiles/task1.dir/home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/RayTracer.cpp.i
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/RayTracer.cpp.i

home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/RayTracer.s: home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/RayTracer.cpp.s
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/RayTracer.s

# target to generate assembly for a file
home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/RayTracer.cpp.s:
	cd /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker && $(MAKE) $(MAKESILENT) -f task1/CMakeFiles/task1.dir/build.make task1/CMakeFiles/task1.dir/home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/RayTracer.cpp.s
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/RayTracer.cpp.s

home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/Scene.o: home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/Scene.cpp.o
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/Scene.o

# target to build an object file
home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/Scene.cpp.o:
	cd /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker && $(MAKE) $(MAKESILENT) -f task1/CMakeFiles/task1.dir/build.make task1/CMakeFiles/task1.dir/home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/Scene.cpp.o
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/Scene.cpp.o

home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/Scene.i: home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/Scene.cpp.i
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/Scene.i

# target to preprocess a source file
home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/Scene.cpp.i:
	cd /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker && $(MAKE) $(MAKESILENT) -f task1/CMakeFiles/task1.dir/build.make task1/CMakeFiles/task1.dir/home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/Scene.cpp.i
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/Scene.cpp.i

home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/Scene.s: home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/Scene.cpp.s
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/Scene.s

# target to generate assembly for a file
home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/Scene.cpp.s:
	cd /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker && $(MAKE) $(MAKESILENT) -f task1/CMakeFiles/task1.dir/build.make task1/CMakeFiles/task1.dir/home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/Scene.cpp.s
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/Scene.cpp.s

home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/SceneBuilder.o: home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/SceneBuilder.cpp.o
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/SceneBuilder.o

# target to build an object file
home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/SceneBuilder.cpp.o:
	cd /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker && $(MAKE) $(MAKESILENT) -f task1/CMakeFiles/task1.dir/build.make task1/CMakeFiles/task1.dir/home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/SceneBuilder.cpp.o
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/SceneBuilder.cpp.o

home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/SceneBuilder.i: home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/SceneBuilder.cpp.i
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/SceneBuilder.i

# target to preprocess a source file
home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/SceneBuilder.cpp.i:
	cd /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker && $(MAKE) $(MAKESILENT) -f task1/CMakeFiles/task1.dir/build.make task1/CMakeFiles/task1.dir/home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/SceneBuilder.cpp.i
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/SceneBuilder.cpp.i

home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/SceneBuilder.s: home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/SceneBuilder.cpp.s
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/SceneBuilder.s

# target to generate assembly for a file
home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/SceneBuilder.cpp.s:
	cd /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker && $(MAKE) $(MAKESILENT) -f task1/CMakeFiles/task1.dir/build.make task1/CMakeFiles/task1.dir/home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/SceneBuilder.cpp.s
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/SceneBuilder.cpp.s

home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/Task.o: home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/Task.cpp.o
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/Task.o

# target to build an object file
home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/Task.cpp.o:
	cd /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker && $(MAKE) $(MAKESILENT) -f task1/CMakeFiles/task1.dir/build.make task1/CMakeFiles/task1.dir/home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/Task.cpp.o
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/Task.cpp.o

home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/Task.i: home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/Task.cpp.i
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/Task.i

# target to preprocess a source file
home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/Task.cpp.i:
	cd /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker && $(MAKE) $(MAKESILENT) -f task1/CMakeFiles/task1.dir/build.make task1/CMakeFiles/task1.dir/home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/Task.cpp.i
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/Task.cpp.i

home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/Task.s: home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/Task.cpp.s
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/Task.s

# target to generate assembly for a file
home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/Task.cpp.s:
	cd /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker && $(MAKE) $(MAKESILENT) -f task1/CMakeFiles/task1.dir/build.make task1/CMakeFiles/task1.dir/home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/Task.cpp.s
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/Task.cpp.s

home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/main.o: home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/main.cpp.o
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/main.o

# target to build an object file
home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/main.cpp.o:
	cd /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker && $(MAKE) $(MAKESILENT) -f task1/CMakeFiles/task1.dir/build.make task1/CMakeFiles/task1.dir/home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/main.cpp.o
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/main.cpp.o

home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/main.i: home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/main.cpp.i
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/main.i

# target to preprocess a source file
home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/main.cpp.i:
	cd /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker && $(MAKE) $(MAKESILENT) -f task1/CMakeFiles/task1.dir/build.make task1/CMakeFiles/task1.dir/home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/main.cpp.i
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/main.cpp.i

home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/main.s: home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/main.cpp.s
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/main.s

# target to generate assembly for a file
home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/main.cpp.s:
	cd /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker && $(MAKE) $(MAKESILENT) -f task1/CMakeFiles/task1.dir/build.make task1/CMakeFiles/task1.dir/home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/main.cpp.s
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/main.cpp.s

home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/task1.o: home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/task1.cpp.o
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/task1.o

# target to build an object file
home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/task1.cpp.o:
	cd /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker && $(MAKE) $(MAKESILENT) -f task1/CMakeFiles/task1.dir/build.make task1/CMakeFiles/task1.dir/home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/task1.cpp.o
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/task1.cpp.o

home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/task1.i: home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/task1.cpp.i
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/task1.i

# target to preprocess a source file
home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/task1.cpp.i:
	cd /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker && $(MAKE) $(MAKESILENT) -f task1/CMakeFiles/task1.dir/build.make task1/CMakeFiles/task1.dir/home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/task1.cpp.i
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/task1.cpp.i

home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/task1.s: home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/task1.cpp.s
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/task1.s

# target to generate assembly for a file
home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/task1.cpp.s:
	cd /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker && $(MAKE) $(MAKESILENT) -f task1/CMakeFiles/task1.dir/build.make task1/CMakeFiles/task1.dir/home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/task1.cpp.s
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/task1.cpp.s

home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/task_builder.o: home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/task_builder.cpp.o
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/task_builder.o

# target to build an object file
home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/task_builder.cpp.o:
	cd /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker && $(MAKE) $(MAKESILENT) -f task1/CMakeFiles/task1.dir/build.make task1/CMakeFiles/task1.dir/home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/task_builder.cpp.o
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/task_builder.cpp.o

home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/task_builder.i: home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/task_builder.cpp.i
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/task_builder.i

# target to preprocess a source file
home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/task_builder.cpp.i:
	cd /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker && $(MAKE) $(MAKESILENT) -f task1/CMakeFiles/task1.dir/build.make task1/CMakeFiles/task1.dir/home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/task_builder.cpp.i
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/task_builder.cpp.i

home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/task_builder.s: home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/task_builder.cpp.s
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/task_builder.s

# target to generate assembly for a file
home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/task_builder.cpp.s:
	cd /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker && $(MAKE) $(MAKESILENT) -f task1/CMakeFiles/task1.dir/build.make task1/CMakeFiles/task1.dir/home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/task_builder.cpp.s
.PHONY : home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/task_builder.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... task1"
	@echo "... home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/BVH.o"
	@echo "... home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/BVH.i"
	@echo "... home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/BVH.s"
	@echo "... home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/RayTracer.o"
	@echo "... home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/RayTracer.i"
	@echo "... home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/RayTracer.s"
	@echo "... home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/Scene.o"
	@echo "... home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/Scene.i"
	@echo "... home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/Scene.s"
	@echo "... home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/SceneBuilder.o"
	@echo "... home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/SceneBuilder.i"
	@echo "... home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/SceneBuilder.s"
	@echo "... home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/Task.o"
	@echo "... home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/Task.i"
	@echo "... home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/Task.s"
	@echo "... home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/main.o"
	@echo "... home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/main.i"
	@echo "... home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/main.s"
	@echo "... home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/task1.o"
	@echo "... home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/task1.i"
	@echo "... home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/task1.s"
	@echo "... home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/task_builder.o"
	@echo "... home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/task_builder.i"
	@echo "... home/thinkpad/Desktop/uni/4.Semester/cg/source/task1/task_builder.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/thinkpad/Desktop/uni/4.Semester/cg/build/build_docker && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

